name: Build SwitchHosts for Arch Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone SwitchHosts
        run: |
          git clone --depth=1 https://github.com/oldj/SwitchHosts.git
          cd SwitchHosts
          git submodule update --init --recursive

      - name: Set up Docker (without containerd.io)
        run: |
          # 安装 Docker 但不安装 containerd.io
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli
          sudo systemctl start docker

          # 验证 Docker 运行
          sudo docker run hello-world

      - name: Build inside Arch Linux container
        run: |
          # 创建构建脚本（与之前相同）
          cat > build.sh << 'EOF'
          #!/bin/bash
          set -e
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git npm python make gcc
          cd /SwitchHosts
          npm install
          npm run build
          mkdir -p pkgbuild
          cat > pkgbuild/PKGBUILD << 'INNEREOF'
          pkgname=switchhosts
          pkgver=$(node -p "require('./package.json').version")
          pkgrel=1
          pkgdesc="Switch hosts quickly!"
          arch=('x86_64')
          url="https://github.com/oldj/SwitchHosts"
          license=('MIT')
          depends=('electron')
          makedepends=('npm' 'git')
          source=("file:///SwitchHosts")
          sha256sums=('SKIP')
          build() {
            cd "$srcdir/SwitchHosts"
            npm install
            npm run build
          }
          package() {
            cd "$srcdir/SwitchHosts"
            install -Dm755 "dist/linux-unpacked/switchhosts" "$pkgdir/usr/bin/switchhosts"
            install -Dm644 "resources/icons/icon.png" "$pkgdir/usr/share/pixmaps/switchhosts.png"
            install -Dm644 "resources/linux/switchhosts.desktop" "$pkgdir/usr/share/applications/switchhosts.desktop"
          }
          INNEREOF
          cd pkgbuild
          makepkg -s --noconfirm
          mkdir -p /mnt/output
          cp *.pkg.tar.zst /mnt/output/
          EOF

          # 运行构建容器
          sudo docker run --rm \
            -v "$(pwd)/SwitchHosts:/SwitchHosts" \
            -v "$(pwd)/output:/mnt/output" \
            archlinux:latest \
            /bin/bash -c "chmod +x /SwitchHosts/build.sh && /SwitchHosts/build.sh"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: switchhosts-archlinux-pkg
          path: output/*.pkg.tar.zst
