name: Build SwitchHosts for Arch Linux

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: 克隆仓库
      uses: actions/checkout@v4
      with:
        repository: oldj/SwitchHosts
        fetch-depth: 0

    - name: 缓存依赖
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ~/.electron
          ~/.cache/electron
          ~/.cache/electron-builder
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: 安装依赖
      run: npm ci --no-audit

    - name: 构建项目
      run: npm run build

    - name: 生成安装包
      run: npm run make

    - name: 上传制品
      uses: actions/upload-artifact@v4
      with:
        name: switchhosts-packages
        path: ./dist/
        retention-days: 3
